
DECLARE 
    X  NUMBER :=10 ;
    Y  NUMBER:=0 ;
    Z NUMBER ; 
    DIVISION_EXP EXCEPTION ; 
BEGIN
    IF Y=0 THEN
        RAISE DIVISION_EXP ;
    ELSE
        Z:=X/Y;
        DBMS_OUTPUT.PUT_LINE('THE DICISION IS '|| Z);
    END IF ;

EXCEPTION 

    WHEN DIVISION_EXP THEN
    DBMS_OUTPUT.PUT_LINE('ARE YOU A DOOFUS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');

END;

/* REVISING THE CASE CONCEPS */

DECLARE 
    X  NUMBER:=10;
BEGIN
    CASE
    WHEN X < 20 THEN 
        DBMS_OUTPUT.PUT_LINE(X);
        X:=X+1;
    END CASE;

EXCEPTION 
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');

END;

/* REVISONG THE LOOP CONCEPT */


DECLARE 
    X  NUMBER:=10;
BEGIN
    WHILE  X <= 20 
        LOOP
            DBMS_OUTPUT.PUT_LINE(X);
            X:=X+1;
        END LOOP ;

EXCEPTION 
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');

END;

/* REVISIONING THE FOR LOOPS CONCEPT AS WELL*/


DECLARE 
    X  NUMBER:=10;
BEGIN
    FOR  X IN  10..20 
    LOOP
        DBMS_OUTPUT.PUT_LINE(X);
    END LOOP ;

EXCEPTION 
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');

END;

