SELECT * FROM EMP;

/*WITH USING THE WHEN CLAUSE */

CREATE OR REPLACE TRIGGER SAL_TGR
BEFORE INSERT OR UPDATE OF SAL ON EMP
FOR EACH ROW
WHEN (NEW.DEPTNO=30)
DECLARE
    MAX_SAL CONSTANT NUMBER:=3000 ;
    CURRENT_MAX NUMBER; 
BEGIN
    CURRENT_MAX:=:NEW.SAL;
    IF CURRENT_MAX > MAX_SAL THEN
        RAISE_APPLICATION_ERROR(-2000,'MAX VALUE REACHED');
    END IF ;
END ;

DESCRIBE EMP;

SELECT * FROM EMP;

INSERT INTO EMP(EMPNO,ENAME,SAL,DEPTNO) VALUES (7769,'PRATIK',3500,30);
INSERT INTO EMP(EMPNO,ENAME,SAL,DEPTNO) VALUES (7769,'PRATIK',3500,20);


ALTER TRIGGER SAL_TGR DISABLE 

/*WITHOUT USING THE WHEN CLAUSE */

CREATE OR REPLACE TRIGGER SAL_TGR_WITHOUT_WHEN
BEFORE INSERT OR UPDATE OF SAL ON EMP
FOR EACH ROW
DECLARE
    MAX_SAL CONSTANT NUMBER:=3000 ;
    CURRENT_MAX NUMBER; 
    CURR_DEPT PLS_INTEGER ;
BEGIN
    CURRENT_MAX:=:NEW.SAL;
    CURR_DEPT:=:NEW.DEPTNO;
    IF CURR_DEPT=30 THEN
        IF CURRENT_MAX > MAX_SAL THEN
            RAISE_APPLICATION_ERROR(-2000,'MAX VALUE REACHED');
        END IF ;
    END IF ;
END ;


ALTER TRIGGER SAL_TGR_WITHOUT_WHEN ENABLE 

INSERT INTO EMP(EMPNO,ENAME,SAL,DEPTNO) VALUES (7259,'PRATIK',5500,30);
INSERT INTO EMP(EMPNO,ENAME,SAL,DEPTNO) VALUES (7769,'PRATIK',3500,20);


SELECT * FROM EMP;

