
CREATE OR REPLACE PROCEDURE FETCH_AURDITRECORD(
        USER_NAME IN AURDITRECORD.USERNAME%TYPE ,
        SYSTEM_DATE IN  AURDITRECORD.SYS_DATE%TYPE,
        EMP_NUMBER IN  EMPLOYEE.EMPNO%TYPE
    )
    IS 
        USR AURDITRECORD.USERNAME%TYPE ;
        SYS_D AURDITRECORD.SYS_DATE%TYPE ;
        EMP_N EMPLOYEE.EMPNO%TYPE ;
       pragma autonomous_transaction ;
    BEGIN
        SELECT * INTO USR,SYS_D,EMP_N
        FROM AURDITRECORD WHERE USERNAME=USER_NAME;
        DBMS_OUTPUT.PUT_LINE(USR ||'==>'|| SYS_D || '==>' || EMP_N );
    END;


CREATE OR REPLACE PROCEDURE DEL_EMP_PROC (
        USERNAME AURDITRECORD.USERNAME%TYPE,
        SYS_DATE AURDITRECORD.SYS_DATE%TYPE,
        EMP_NUM IN EMPLOYEE.EMPNO%TYPE
    )
    IS
    BEGIN
        DELETE FROM EMPLOYEE WHERE EMPNO=EMP_NUM;
        IF SQL%ROWCOUNT!= 0 THEN 
             FETCH_AURDITRECORD(USER_NAME=>USERNAME,SYSTEM_DATE=>SYS_DATE,EMP_NUMBER=>EMP_NUM);
        ELSIF SQL%ROWCOUNT=0 THEN
            DBMS_OUTPUT.PUT_LINE('DATA NOT FOUND');
        ELSE
            RAISE_APPLICATION_ERROR(1000,'SOMETHING WENT WRONG');
        END IF;
    END;