
SELECT * FROM EMPLOYEE

INSERT INTO STORES_EMPLOYEE

DELETE FROM EMPLOYEE WHERE EMPNO=7698;

/* CREATING THE AUDIT TABLE  */

CREATE TABLE AURDITRECORD(
    USERNAME VARCHAR2(255),
    SYS_DATE DATE,
    EMP_NUMBER NUMBER
);

/* CREATING THE PKG HEADER */

CREATE OR REPLACE  PACKAGE EMP_DEL_AUDIT_PKG IS 
    PROCEDURE EMP_DEL_PROC (
        EMP_NO IN NUMBER 
    ) ;
END EMP_DEL_AUDIT_PKG ;

CREATE OR REPLACE  PACKAGE BODY  EMP_DEL_AUDIT_PKG IS
PROCEDURE FETCH_AURDITRECORD
(
    USR_NAME_VAL IN VARCHAR2,
    SYSTEM_DATE_VAR IN  DATE,
    EMP_NUMB IN  NUMBER
)
IS 
    PRAGMA AUTONOMOUS_TRANSACTION ;
BEGIN
    INSERT INTO AURDITRECORD(USERNAME,SYS_DATE,EMP_NUMBER ) VALUES (USR_NAME_VAL,SYSTEM_DATE_VAR,EMP_NUMB);
END FETCH_AURDITRECORD

PROCEDURE DEL_EMP_PROC (

    USER_NAME_VAR AURDITRECORD.USERNAME%TYPE,
    SYS_DATE_VAR AURDITRECORD.SYS_DATE%TYPE,
    EMP_NUM_VAR IN EMPLOYEE.EMPNO%TYPE
)
IS
BEGIN
    DELETE FROM EMPLOYEE WHERE EMPNO=EMP_NUM;
    IF SQL%ROWCOUNT != 0 THEN 
            FETCH_AURDITRECORD(USR_NAME_VAL=>USER_NAME_VAR,SYSTEM_DATE_VAR=>SYS_DATE_VAR,EMP_NUMB=>EMP_NUM_VAR);
    ELSIF SQL%ROWCOUNT=0 THEN
        DBMS_OUTPUT.PUT_LINE('DATA NOT FOUND');
    ELSE
        RAISE_APPLICATION_ERROR(1000,'SOMETHING WENT WRONG');
    END IF;
END DEL_EMP_PROC


USR_NAME AURDITRECORD.USERNAME%TYPE ;
SYS_DATE_VAL AURDITRECORD.SYS_DATE%TYPE ;
BEGIN
    SELECT USER,SYSDATE INTO USR_NAME,SYS_DATE_VAL
    FROM DUAL;
    DEL_EMP_PROC(USER_NAME_VAR=>USR_NAME,SYS_DATE_VAR=>SYS_DATE_VAL,EMP_NUM_VAR=>7788);
END ;

END EMP_DEL_AUDIT_PKG ;

SELECT SYSDATE FROM DUAL 


/* TRYING INDIVIDUALLY */

CREATE OR REPLACE PROCEDURE FETCH_AURDITRECORD_TEST(
        USER_NAME IN AURDITRECORD.USERNAME%TYPE ,
        SYSTEM_DATE IN  AURDITRECORD.SYS_DATE%TYPE,
        EMP_NUMBER IN  EMPLOYEE.EMPNO%TYPE
    )
    IS 
        USR AURDITRECORD.USERNAME%TYPE ;
        SYS_D AURDITRECORD.SYS_DATE%TYPE ;
        EMP_N EMPLOYEE.EMPNO%TYPE ;
    BEGIN
        INSERT INTO AURDITRECORD(USERNAME,SYS_DATE,EMP_NUMBER) VALUES (USER_NAME,SYSTEM_DATE,EMP_NUMBER);
        -- SELECT USERNAME,SYS_DATE,EMP_NUMBER INTO USR,SYS_D,EMP_N
        -- FROM  AURDITRECORD WHERE USERNAME=USER_NAME;
        -- DBMS_OUTPUT.PUT_LINE(USR ||'==>'|| SYS_D || '==>' || EMP_N );
    END;


CREATE OR REPLACE PROCEDURE DEL_EMP_PROC (
        USERNAME AURDITRECORD.USERNAME%TYPE,
        SYS_DATE AURDITRECORD.SYS_DATE%TYPE,
        EMP_NUM IN EMPLOYEE.EMPNO%TYPE
    )
    IS
    BEGIN
        DELETE FROM EMPLOYEE WHERE EMPNO=EMP_NUM;
        IF SQL%ROWCOUNT!= 0 THEN 
             FETCH_AURDITRECORD_TEST(USER_NAME=>USERNAME,SYSTEM_DATE=>SYS_DATE,EMP_NUMBER=>EMP_NUM);
        ELSE
            DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');
        END IF;
    END;

DECLARE
    USR_NAME AURDITRECORD.USERNAME%TYPE ;
    SYS_DATE_VAL AURDITRECORD.SYS_DATE%TYPE;
BEGIN
        SELECT USER,SYSDATE INTO USR_NAME ,SYS_DATE_VAL
        FROM DUAL;
        DEL_EMP_PROC(USERNAME=>USR_NAME,SYS_DATE=>SYS_DATE_VAL,EMP_NUM=>7566);
END ;

SELECT * FROM AURDITRECORD ;


/* TESTING THE SAME */

/*testing successful */


CREATE OR REPLACE PROCEDURE DEL_EMP_PROC_TEST (
        USERNAME AURDITRECORD.USERNAME%TYPE,
        SYS_DATE AURDITRECORD.SYS_DATE%TYPE,
        EMP_NUM IN EMPLOYEE.EMPNO%TYPE
    )
    IS
    BEGIN
        DELETE FROM EMPLOYEE WHERE EMPNO=EMP_NUM;
        IF SQL%ROWCOUNT!= 0 THEN 
             DBMS_OUTPUT.PUT_LINE('DATA DELETED SUCCESSFULLY ');
        ELSE
            DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');
        END IF;
    END;

DECLARE
    USR_NAME AURDITRECORD.USERNAME%TYPE ;
    SYS_DATE_VAL AURDITRECORD.SYS_DATE%TYPE;
BEGIN
        SELECT USER,SYSDATE INTO USR_NAME ,SYS_DATE_VAL
        FROM DUAL;
        DEL_EMP_PROC_TEST(USERNAME=>USR_NAME,SYS_DATE=>SYS_DATE_VAL,EMP_NUM=>7839);
END ;


/*TEST CASE BASIS*/

CREATE OR REPLACE PROCEDURE FETCH_AURDITRECORD(
        USER_NAME IN AURDITRECORD.USERNAME%TYPE ,
        SYSTEM_DATE IN  AURDITRECORD.SYS_DATE%TYPE,
        EMP_NUMBER IN  EMP.EMPNO%TYPE
    )
    IS 
    BEGIN
        INSERT INTO AURDITRECORD(USERNAME,SYS_DATE,EMP_NUMBER)VALUES(USER_NAME,SYSTEM_DATE,EMP_NUMBER);
        DBMS_OUTPUT.PUT_LINE('TRANACTION BEEN RECORDED');
    END;

/*MODIFY PKG BOSY AS */
CREATE OR REPLACE  PACKAGE BODY  EMP_DEL_AUDIT_PKG IS
USR_NAME_VAL AURDITRECORD.USERNAME%TYPE ;
SYS_DATE_VAL AURDITRECORD.SYS_DATE%TYPE ;
PROCEDURE FETCH_AURDITRECORD
(
    USR_NAME_VAL IN AURDITRECORD.USERNAME%TYPE ,
    SYSTEM_DATE_VAR IN  AURDITRECORD.SYS_DATE%TYPE,
    EMP_NUMB IN  EMPLOYEE.EMPNO%TYPE
)
IS 
    PRAGMA AUTONOMOUS_TRANSACTION ;
BEGIN
    INSERT INTO AURDITRECORD(USERNAME,SYS_DATE,EMP_NUMBER ) VALUES (USR_NAME_VAL,SYSTEM_DATE_VAR,EMP_NUMB);
END FETCH_AURDITRECORD;
PROCEDURE DEL_EMP_PROC (

    USER_NAME_VAR AURDITRECORD.USERNAME%TYPE,
    SYS_DATE_VAR AURDITRECORD.SYS_DATE%TYPE,
    EMP_NUM_VAR IN EMPLOYEE.EMPNO%TYPE
)
IS
BEGIN
    DELETE FROM EMPLOYEE WHERE EMPNO=EMP_NUM_VAR;
    IF SQL%ROWCOUNT != 0 THEN 
            FETCH_AURDITRECORD(USR_NAME_VAL=>USER_NAME_VAR,SYSTEM_DATE_VAR=>SYS_DATE_VAR,EMP_NUMB=>EMP_NUM_VAR);
    ELSIF SQL%ROWCOUNT=0 THEN
        DBMS_OUTPUT.PUT_LINE('DATA NOT FOUND');
    END IF;
END DEL_EMP_PROC ;
BEGIN
    SELECT USER,SYSDATE INTO USR_NAME_VAL,SYS_DATE_VAL
    FROM DUAL;
    DEL_EMP_PROC(USER_NAME_VAR=>USR_NAME_VAL,SYS_DATE_VAR=>SYS_DATE_VAL,EMP_NUM_VAR=>7788);
END EMP_DEL_AUDIT_PKG ;












