
SELECT * FROM DEPT;

SELECT * FROM EMP

CREATE OR REPLACE PROCEDURE EMP_PROC_NEW
(
    DEPT_NO IN DEPT.DEPTNO%TYPE, /* BY DEFAULT ITS IN TYPE ONLY*/
    EMP_CUR_NEW OUT Sys_RefCursor  /* DEFINING THE CURSOR AS OUTPUT VALUE THE PROCEDURE WILL CREATE */
)
IS 
BEGIN
    OPEN EMP_CUR_NEW FOR SELECT * FROM EMP WHERE DEPTNO=DEPT_NO;
END ;

CREATE OR REPLACE PROCEDURE EMP_GET_PROC
IS
    EMP_NUM EMP.EMPNO%TYPE ;
    E_NAME EMP.ENAME%TYPE;
    EMP_DATA_CUR Sys_RefCursor ;
BEGIN
    EMP_PROC_NEW(10,EMP_DATA_CUR);
    LOOP
        FETCH EMP_DATA_CUR INTO EMP_NUM,E_NAME ;
        EXIT WHEN EMP_DATA_CUR%NOTFOUND ;
        DBMS_OUTPUT.PUT_LINE(EMP_NUM || '=====>' ||E_NAME );
    END LOOP;
END;