DECLARE 

TOTAL_AMOUNT NUMBER:=40;

DISCOUNT NUMBER:=0;

OUTPUT NUMBER:=0;

BEGIN

    IF (TOTAL_AMOUNT>100)
        THEN 
        DISCOUNT:=0.2;
        OUTPUT:=TOTAL_AMOUNT*DISCOUNT;
        DBMS_OUTPUT.PUT_LINE(OUTPUT);
    ELSIF (TOTAL_AMOUNT > 50 AND TOTAL_AMOUNT < 100) THEN
        DISCOUNT:=0.4;
        OUTPUT:=TOTAL_AMOUNT*DISCOUNT;
        DBMS_OUTPUT.PUT_LINE(OUTPUT);
    ELSE
        DISCOUNT:=0.5;
        OUTPUT:=TOTAL_AMOUNT*DISCOUNT;
        DBMS_OUTPUT.PUT_LINE(OUTPUT);
    END IF;

END;