
/* CURSOR DEMO 1 */

SELECT * FROM STORES_EMPLOYEE

/* USING IT INSIDE THE PROCEDURE */

DECLARE 
    OUTPUT NUMBER ;
    CURSOR EMP_CURSOR IS SELECT STORES_ID  FROM STORES_EMPLOYEE ;
BEGIN
    OPEN EMP_CURSOR;
    FETCH EMP_CURSOR INTO OUTPUT;
    DBMS_OUTPUT.PUT_LINE(OUTPUT);
    CLOSE EMP_CURSOR;
END 

/* USING IT INSIDE THE STORED_PROCEDURE */

CREATE OR REPLACE PROCEDURE EMP_SRC_PROC_NEW
(
    S_CITY IN VARCHAR2
)
IS
    OUTPUT NUMBER ;
    CURSOR EMP_CURSOR IS SELECT STORES_ID FROM STORES_EMPLOYEE WHERE CITY=S_CITY ;
BEGIN
    OPEN EMP_CURSOR;
    FETCH EMP_CURSOR INTO OUTPUT;
    DBMS_OUTPUT.PUT_LINE(OUTPUT);
    CLOSE EMP_CURSOR;
END 


BEGIN

EMP_SRC_PROC_NEW(S_CITY=>'CUTTACK');

END