
/* PARAMETER CURSOR WITH LOOP IN ANONYMOUS BLOCK  */

DECLARE 
    S_STORE NUMBER ;
    S_CITY VARCHAR2(255);
    CURSOR PARA_CUR (STORE_NO NUMBER ) IS SELECT STORES_ID , CITY FROM STORES_EMPLOYEE WHERE  STORES_ID=STORE_NO;
BEGIN
    OPEN PARA_CUR(STORE_NO=>1003);
    LOOP 
        FETCH PARA_CUR INTO S_STORE,S_CITY;
        DBMS_OUTPUT.PUT_LINE(S_STORE || '============>' || S_CITY );
        -- EXIT WHEN PARA_CUR%NOTFOUND ;
        IF PARA_CUR%NOTFOUND THEN
            EXIT ;
        END IF ;
    END LOOP;
END ;

/* DEFAULT PARAMETER CURSOR WITH LOOP IN ANONYMOUS BLOCK  */

DECLARE 
    S_STORE NUMBER ;
    S_CITY VARCHAR2(255);
    CURSOR PARA_CUR (STORE_NO NUMBER:=1001 ) IS SELECT STORES_ID , CITY FROM STORES_EMPLOYEE WHERE  STORES_ID=STORE_NO;
BEGIN
    -- OPEN PARA_CUR(STORE_NO=>1003);
    OPEN PARA_CUR;
    LOOP 
        FETCH PARA_CUR INTO S_STORE,S_CITY;
        DBMS_OUTPUT.PUT_LINE(S_STORE || '============>' || S_CITY );
        -- EXIT WHEN PARA_CUR%NOTFOUND ;
        IF PARA_CUR%NOTFOUND THEN
            EXIT ;
        END IF ;
    END LOOP;
END ;

/*HANDLING THE EXCEPTIONRAISED WHEN ITS A PARAMETERIZED SQL STATEMENT BUT NOT PROVIDING THE VALUE FOR THE CURSOR PARAMETER*/

DECLARE 
    S_STORE NUMBER ;
    S_CITY VARCHAR2(255);
    CURSOR PARA_CUR (STORE_NO NUMBER ) IS SELECT STORES_ID , CITY FROM STORES_EMPLOYEE WHERE  STORES_ID=STORE_NO;
BEGIN
    OPEN PARA_CUR;
    LOOP 
        FETCH PARA_CUR INTO S_STORE,S_CITY;
        DBMS_OUTPUT.PUT_LINE(S_STORE || '============>' || S_CITY );
        -- EXIT WHEN PARA_CUR%NOTFOUND ;
        IF PARA_CUR%NOTFOUND THEN
            EXIT ;
        END IF ;
    END LOOP;
END ;

/* THE ABOVE QUERY WILL PROVIDE THE BELOW ERROR HENCE  WE CAN HANDLE THE SAME AS */

-- ORA-06550: line 6, column 5:
-- PLS-00306: wrong number or types of arguments in call to 'PARA_CUR' /*HANDLING THIS ERROR AS THIS IS THE MAIN ERROR */
-- ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_210200", line 673
-- ORA-06550: line 6, column 5:
-- PL/SQL: SQL Statement ignored
-- ORA-06512: at "SYS.DBMS_SYS_SQL", line 1658
-- ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_210200", line 659
-- ORA-06512: at "APEX_210200.WWV_FLOW_DYNAMIC_EXEC", line 1829

DECLARE 
    S_STORE NUMBER ;
    S_CITY VARCHAR2(255);
    CURSOR PARA_CUR (STORE_NO NUMBER:=1001 ) IS SELECT STORES_ID , CITY FROM STORES_EMPLOYEE WHERE  STORES_ID=STORE_NO;
    -- PARA_EXP EXCEPTION ;
    -- PRAGMA EXCEPTION_INIT(PARA_EXP,-06550);

BEGIN
    -- OPEN PARA_CUR(STORE_NO=>1001);
    OPEN PARA_CUR(STORE_NO=>1003) ;
    LOOP 
        FETCH PARA_CUR INTO S_STORE,S_CITY;
        DBMS_OUTPUT.PUT_LINE(S_STORE || '============>' || S_CITY );
        -- EXIT WHEN PARA_CUR%NOTFOUND ;
        IF PARA_CUR%NOTFOUND THEN
            EXIT ;
        END IF ;
    END LOOP;
EXCEPTION
    WHEN  STORAGE_ERROR THEN
     DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG' );
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG' );

END ;