/*CREATING A VIEW FOR BOTH EMP AND DEPT TABLE AS INNER JOIN */
SELECT
    *
FROM
    EMP;

SELECT
    *
FROM
    DEPT;

SELECT DISTINCT
    DEPTNO
FROM
    EMP;

SELECT
    DEPTNO
FROM
    DEPT;

CREATE OR REPLACE VIEW EMPDEPTVIEW AS
--HERE WE ARE USING THE JOIN STYATEMENT FOR THE BOTH EMP AND DEPT TABLE 
    SELECT
        E.*,
        D.DNAME,
        D.LOC
    FROM
        EMP E
        INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;


/* NOW WE ARE ONLY GRANTING THE SELECT ACCESS TO THE USER PRATIK*/

GRANT SELECT ON EMPDEPTVIEW TO PRATIK;

/* NOW WRTRING THE INSTEAD  TRIGGER WHICH  WILL BE FIRED ON BEHALF OF THE DML ACTION ON  VIEW  */

CREATE OR REPLACE TRIGGER EMPDEPT_TGR INSTEAD OF
    INSERT ON ADMIN.EMPDEPTVIEW
    FOR EACH ROW
DECLARE
    V_DEPTNO   PLS_INTEGER;
BEGIN
    V_DEPTNO :=:NEW.DEPTNO;
    IF
        V_DEPTNO NOT IN (
            10,
            20,
            30
        )
    THEN
        INSERT INTO ADMIN.DEPT (
            DEPTNO,
            DNAME,
            LOC
        ) VALUES (
            V_DEPTNO,
            :NEW.DNAME,
            :NEW.LOC
        );

        INSERT INTO ADMIN.EMP (
            EMPNO,
            ENAME,
            SAL,
            DEPTNO
        ) VALUES (
            :NEW.EMPNO,
            :NEW.ENAME,
            :NEW.SAL,
            :NEW.DEPTNO
        );

        DBMS_OUTPUT.PUT_LINE('TRIGGER EXECUTION SUCCESSFUL');
    END IF;

END;

ALTER TRIGGER EMPDEPT_TGR DISABLE;

ALTER TRIGGER EMPDEPT_TGR ENABLE;

SELECT
    *
FROM
    ALL_TRIGGERS
WHERE
    TRIGGER_NAME = 'EMPDEPT_TGR';

INSERT INTO EMPDEPTVIEW (
    EMPNO,
    ENAME,
    SAL,
    DEPTNO,
    DNAME,
    LOC
) VALUES (
    7205,
    'PRATIK',
    2000,
    60,
    'ACCOUNT',
    'BANGALORE'
);

SELECT
    *
FROM
    DEPT;