SELECT * FROM STORES_EMPLOYEE

INSERT INTO STORES_EMPLOYEE(STORES_ID,CITY) VALUES (1007,'CUTTACK')

CREATE OR REPLACE PROCEDURE STORES_EMPLOYEE_PROC
(    
    STORES_ID_NUMBER IN NUMBER
)
AS
    S_STORES_ID STORES_EMPLOYEE.STORES_ID%TYPE;
    S_CITY STORES_EMPLOYEE.CITY%TYPE ;

BEGIN

    SELECT STORES_ID,CITY INTO S_STORES_ID,S_CITY
    FROM STORES_EMPLOYEE WHERE STORES_ID=STORES_ID_NUMBER;

    DBMS_OUTPUT.PUT_LINE(S_STORES_ID);
    DBMS_OUTPUT.PUT_LINE(S_CITY);

END;


/*CALLING THE PROCEDURE WITHOUT EXCEPTION BLOCK */

BEGIN

STORES_EMPLOYEE_PROC(STORES_ID_NUMBER =>1007);

END;

/* CREATING CONSIDERING THE EXCEPTION CLAUSE AS NO_DATA_FOUND */

CREATE OR REPLACE PROCEDURE STORES_EMPLOYEE_PROC
(
    S_ID IN NUMBER
)
AS 
    S_ID_NO STORES_EMPLOYEE.STORES_ID%TYPE;
    S_CITY  STORES_EMPLOYEE.CITY%TYPE;

BEGIN

    SELECT STORES_ID,CITY INTO S_ID_NO,S_CITY
    FROM STORES_EMPLOYEE WHERE STORES_ID=S_ID;

    DBMS_OUTPUT.PUT_LINE(S_ID_NO);
    DBMS_OUTPUT.PUT_LINE(S_CITY);

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('RECORDS NOT AVAILABLE');

END STORES_EMPLOYEE_PROC;

/*CALLING THE PROCEDURE*/


BEGIN

STORES_EMPLOYEE_PROC(S_ID=>1007);

END;

/* HANDLING TOO_MANY ROWS EXCEPTION */

CREATE OR REPLACE PROCEDURE STORES_EMPLOYEE_PROC
(
    S_CITY  IN  VARCHAR2
)
AS 
    S_ID STORES_EMPLOYEE.STORES_ID%TYPE;
    S_CITY_NAME STORES_EMPLOYEE.CITY%TYPE;

BEGIN
    
    SELECT STORES_ID,CITY INTO S_ID,S_CITY_NAME
    FROM STORES_EMPLOYEE WHERE CITY=S_CITY;

    DBMS_OUTPUT.PUT_LINE('STORES_ID: ' || S_ID );
    DBMS_OUTPUT.PUT_LINE('CITY NAME: ' || S_CITY_NAME );

    EXCEPTION

    WHEN NO_DATA_FOUND THEN 
    DBMS_OUTPUT.PUT_LINE('RECORD NOT FOUND ');
    WHEN TOO_MANY_ROWS THEN 
    DBMS_OUTPUT.PUT_LINE('MULTIPLE RECORD FOUND ');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR ! ERROR !');

END STORES_EMPLOYEE_PROC;


/*CALLING THE PROCEDURE*/

BEGIN

STORES_EMPLOYEE_PROC(S_CITY=>'CUTTACK');

END;

