
/*EXPLICIT CURSOR WITH SIMPLE LOOP CONDITION ANONYMOUS BLOCK*/

DECLARE 
    S_STORES STORES_EMPLOYEE.STORES_ID%TYPE ;
    S_CITY STORES_EMPLOYEE.CITY%TYPE ;
    CURSOR STORE_CUR IS SELECT STORES_ID,CITY FROM STORES_EMPLOYEE ;
BEGIN
    OPEN STORE_CUR ;
    LOOP
        FETCH STORE_CUR INTO S_STORES,S_CITY;
        DBMS_OUTPUT.PUT_LINE(S_STORES || '------>' || S_CITY );
        EXIT WHEN STORE_CUR%NOTFOUND;
    END LOOP ;
    CLOSE STORE_CUR ;
END ;

/* HERE USING THE SIMPLE LOOP USING THE IF BLOCK */

DECLARE 
    S_STORES STORES_EMPLOYEE.STORES_ID%TYPE ;
    S_CITY STORES_EMPLOYEE.CITY%TYPE ;
    CURSOR STORE_CUR IS SELECT STORES_ID,CITY FROM STORES_EMPLOYEE ;
BEGIN
    OPEN STORE_CUR ;
    LOOP
        FETCH STORE_CUR INTO S_STORES,S_CITY;
        DBMS_OUTPUT.PUT_LINE(S_STORES || '------>' || S_CITY );
        IF STORE_CUR%NOTFOUND THEN 
            EXIT ;
        END IF ;
    END LOOP ;
    CLOSE STORE_CUR ;
END ;