
/* IMPLECIT CURSORS */

SELECT * FROM STORES_EMPLOYEE;

CREATE OR REPLACE PROCEDURE DML_PROC
(
    S_STORES IN STORES_EMPLOYEE.STORES_ID%TYPE,
    S_CITY IN STORES_EMPLOYEE.CITY%TYPE

)
IS 
    OUTPUT1 BOOLEAN;
    OUTPUT2 BOOLEAN;
    DUP_REC EXCEPTION;
    PRAGMA EXCEPTION_INIT(DUP_REC,-00001);
BEGIN
    INSERT INTO STORES_EMPLOYEE (STORES_ID,CITY) VALUES (S_STORES,S_CITY);
    DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
    OUTPUT1:=SQL%FOUND;
    OUTPUT2:=SQL%NOTFOUND;
    IF OUTPUT1 THEN
        DBMS_OUTPUT.PUT_LINE('SUCCESSFUL TRANACTION ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('UNSUCCESSFUL TRANACTION');
    END IF ;

    IF OUTPUT2 THEN
        DBMS_OUTPUT.PUT_LINE('UNSUCCESSFUL TRANACTION ');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SUCCESSFUL TRANACTION');
    END IF ;


EXCEPTION
    WHEN DUP_REC THEN
    DBMS_OUTPUT.PUT_LINE('YOU ARE WRITING THE DUPLICATED RECORD DOOFUS');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');

END DML_PROC;


BEGIN

DML_PROC(S_STORES=>1009,S_CITY=>'TANGI');

END
