/*DEFINING THE PACKAGE HEADER */

CREATE OR REPLACE PACKAGE FWD_PKG IS
FUNCTION CALLING_FUNC(
    INPUT_VAR IN  NUMBER
)RETURN NUMBER;
END FWD_PKG ;

/*NOW CREATING TRHE CO DEPENDENT FUNCTION */

/*DEFINING THE PACKAGE BODY */
CREATE OR REPLACE PACKAGE BODY FWD_PKG IS 
FUNCTION CALLED_FUNC(
    CALLED_VAR IN NUMBER
)RETURN NUMBER ;
FUNCTION CALLING_FUNC(
    INPUT_VAR IN  NUMBER
)RETURN NUMBER
IS 
    FETCH_VAR NUMBER;
    OUTPUT_VAR NUMBER;
    RESULT_VAR NUMBER;
BEGIN
    FETCH_VAR:=INPUT_VAR+10;
    OUTPUT_VAR:=FETCH_VAR*10;
    RESULT_VAR:=CALLED_FUNC(OUTPUT_VAR);
    DBMS_OUTPUT.PUT_LINE(FETCH_VAR);
    DBMS_OUTPUT.PUT_LINE(OUTPUT_VAR);
    DBMS_OUTPUT.PUT_LINE(RESULT_VAR);
    RETURN OUTPUT_VAR ;
END CALLING_FUNC ;
FUNCTION CALLED_FUNC(
    CALLED_VAR IN NUMBER
)RETURN NUMBER 
IS 
    OUTPUT NUMBER ;
BEGIN
    OUTPUT:=CALLED_VAR*5;
    DBMS_OUTPUT.PUT_LINE(OUTPUT);
    RETURN OUTPUT ;
END CALLED_FUNC ;
END FWD_PKG ;


/* CALLLING THE PACKAGE */

SELECT FWD_PKG.CALLING_FUNC(17) FROM DUAL;

/* CALLING THROUGH THE ANONYMOUS BLOCK*/

DECLARE 
OUTPUT_NUMBER NUMBER;
BEGIN
OUTPUT_NUMBER:=FWD_PKG.CALLING_FUNC(17);
END 



