CREATE OR REPLACE FUNCTION FUNC_DATE
(
    P_CITY     IN VARCHAR2
) 
RETURN NUMBER 
AS
    NUM_OF_SALES NUMBER:=0;
BEGIN
    SELECT STORES_ID INTO  NUM_OF_SALES 
    FROM STORES_EMPLOYEE WHERE CITY=P_CITY;

    RETURN NUM_OF_SALES;

END FUNC_DATE;

/* ANOTHER EXAMPLE */

SELECT FUNC_DATE(P_CITY=>'KERELA') FROM DUAL;

CREATE OR REPLACE FUNCTION FUNC_CITY
(
    P_STORES_ID IN NUMBER
)
RETURN VARCHAR2
AS
    V_CITY VARCHAR2(50):='';
BEGIN
    SELECT CITY INTO V_CITY
    FROM STORES_EMPLOYEE WHERE STORES_ID= P_STORES_ID;

    RETURN V_CITY;

END FUNC_CITY ;

SELECT FUNC_CITY(P_STORES_ID=>1005) FROM DUAL