/* PRAGMA EXCEPTION_INIT(USER DEFINED EXCEPTION , ERROR CODE ) */

DECLARE 
    X NUMBER:=10 ;
    Y NUMBER:=0 ;
    Z NUMBER ;
    ZERO_DIV EXCEPTION ;
    PRAGMA EXCEPTION_INIT(ZERO_DIV,-01476);

BEGIN
    Z:=X/Y;
    DBMS_OUTPUT.PUT_LINE(Z);

EXCEPTION 
    WHEN ZERO_DIV THEN
    DBMS_OUTPUT.PUT_LINE('CANT DEVIDE BY ZERO');

END;


/* WE CAN ALSO USE IT IN THE EMP AND DEPT TABLE WHICH ARE RELATED THROUGH PARENT CHILD RELATIONSHIP */

SELECT * FROM EMP;


DELETE FROM EMP WHERE EMPNO=7839; /*-02292 ERROR CODE FETCHED*/

/* HERE WE ARE USING THE SAME IN THE ANONYMOUS BLOCK */

DECLARE
    EMP_NO NUMBER :=7839;
    CHILD_FND EXCEPTION ;
    PRAGMA EXCEPTION_INIT(CHILD_FND,-02292);
BEGIN
    DELETE FROM EMP WHERE EMPNO=EMP_NO;
    DBMS_OUTPUT.PUT_LINE('DATA DETETED SUCCESSFULLY');
EXCEPTION
    WHEN CHILD_FND THEN
    DBMS_OUTPUT.PUT_LINE('TABLES ARE IN A RELATIONSHIP TRY TO REMOTE THE RECORD FROM THE CHILD TABLE FIRST');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');
END ;

/* IMPLEMENTING THE SAME IN THE FORM OF A PROCEDURE*/

CREATE OR REPLACE PROCEDURE EMP_DEPT_PROC
(
    EMP_NO IN NUMBER
)
IS
    CHILD_FOUND EXCEPTION ;
    PRAGMA EXCEPTION_INIT(CHILD_FOUND,-02292);
BEGIN
    DELETE FROM EMP WHERE EMPNO=EMP_NO ;
    DBMS_OUTPUT.PUT_LINE('DATA DELETED SUCCESSFULLY');
EXCEPTION
    WHEN CHILD_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('TABLES ARE IN RELATIONSHIP TRY REMOVING THE ELEMENT FROM THE CHILD TABLE');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT VERY WRONG');

END EMP_DEPT_PROC ;

/* CALLING THE FUNCTION FOR THE SAME */

BEGIN

EMP_DEPT_PROC(EMP_NO=>7839);

END

/* WE CAN ALSO IMPLEMENT THAT USING THE FUNCTION AS BELOW */

CREATE OR REPLACE FUNCTION EMP_DEPT_FUNC
(
    EMP_NO IN NUMBER 
) RETURN VARCHAR2
IS 
    CHILD_REC_FND EXCEPTION ;
    PRAGMA EXCEPTION_INIT(CHILD_REC_FND,-02292);
    RESULT_VAR VARCHAR2(255) ;

BEGIN
    DELETE FROM EMP WHERE EMPNO=EMP_NO;
    

EXCEPTION 
    WHEN CHILD_REC_FND THEN
    DBMS_OUTPUT.PUT_LINE('TABLES ARE IN RELATIONSHIP TRY REMOVING THE ELEMENT FROM THE CHILD TABLE');
    RESULT_VAR:='DELETION SUCCESSFUL';
    RETURN RESULT_VAR ;
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT REALLY WRONG');

END EMP_DEPT_FUNC ;

/*CALLING THE FUNCTION  FOR THE SAME */

DECLARE
    RESULT_OUTPUT VARCHAR2(255) ;
BEGIN
    RESULT_OUTPUT:=EMP_DEPT_FUNC(EMP_NO=>7839);
END
