
CREATE OR REPLACE PROCEDURE FUNC_PROC
(
    NUM1    IN  NUMBER,
    NUM2    IN  NUMBER, 
    RESULT_VAR OUT NUMBER
)
AS 
BEGIN
    RESULT_VAR:=NUM1+NUM2;
    DBMS_OUTPUT.PUT_LINE (RESULT_VAR );
END FUNC_PROC;

DECLARE
RESULT_NUM NUMBER;
BEGIN
FUNC_PROC(NUM1=>20,NUM2=>20,RESULT_VAR=>RESULT_NUM);
END;


CREATE OR REPLACE PROCEDURE FUNC_PROCEDURE
(
    VAL1    IN NUMBER,
    VAL2    IN NUMBER
)
AS 
    TOTAL_VALUE NUMBER;
BEGIN
    TOTAL_VALUE:=VAL1+VAL2;
    DBMS_OUTPUT.PUT_LINE(TOTAL_VALUE);
END;



BEGIN

FUNC_PROCEDURE(10,20);

END;

BEGIN

FUNC_PROCEDURE(VAL1=>10,VAL2=>20);

END;


SELECT COUNT(1) FROM STORES_EMPLOYEE

SELECT * FROM STORES_EMPLOYEE


CREATE OR REPLACE PROCEDURE FUNC_OUT_PROCEDURE
(
    STORES_ID IN NUMBER DEFAULT 1005,
    CITY IN VARCHAR2 DEFAULT 'KERELA',
    COUNT_VAL OUT NUMBER
)
AS 
BEGIN
    INSERT INTO STORES_EMPLOYEE(STORES_ID,CITY) VALUES(STORES_ID,CITY);
    DBMS_OUTPUT.PUT_LINE('INSERTED RECORD');
    SELECT COUNT(1) INTO COUNT_VAL FROM STORES_EMPLOYEE;
END;

DECLARE 
COUNT_VALUE NUMBER;
BEGIN
FUNC_OUT_PROCEDURE(COUNT_VAL=>COUNT_VALUE);
END;


/*EXECUTING IN THE IN OUT MODE */

CREATE OR REPLACE PROCEDURE FUNC_INOUT_PROCEDURE
(
    STORES_ID IN OUT NUMBER,
    CITY IN VARCHAR2 DEFAULT 'PUNE'

)
AS 
BEGIN
    INSERT INTO STORES_EMPLOYEE(STORES_ID,CITY) VALUES(STORES_ID,CITY);
    SELECT COUNT(1) INTO STORES_ID FROM STORES_EMPLOYEE;
END;

DECLARE 

STORE_COUNT NUMBER;

BEGIN
FUNC_INOUT_PROCEDURE(STORES_ID)
END


SELECT * FROM STORES_EMPLOYEE ORDER BY STORES_ID  DESC;

SELECT COUNT(STORES_ID) FROM STORES_EMPLOYEE;

CREATE OR REPLACE PROCEDURE FUNC_INOUT_PROC
(
    S_ID IN NUMBER,
    S_CITY IN VARCHAR2,
    TBL_COUNT IN OUT NUMBER
)
AS
BEGIN
    INSERT INTO STORES_EMPLOYEE(STORES_ID,CITY) VALUES(S_ID,S_CITY);
    DBMS_OUTPUT.PUT_LINE('RECORD INSERTED SUCCESSFULLY');
    SELECT COUNT(STORES_ID) INTO TBL_COUNT FROM STORES_EMPLOYEE;
    DBMS_OUTPUT.PUT_LINE(TBL_COUNT);
END FUNC_INOUT_PROC;


DECLARE 
TBL_COUNT_VAR NUMBER;
BEGIN
FUNC_INOUT_PROC(1006,'KOCHI',TBL_COUNT=>TBL_COUNT_VAR);
END;

SELECT * FROM STORES_EMPLOYEE;





