/* SIMPLE RECORD DEMO EXAMPLE ON THE STORES_EMPLOYEE OBJECT */

DECLARE
    STORE_INFO STORES_EMPLOYEE%ROWTYPE;
    S_STORES NUMBER;
BEGIN
        S_STORES:=1003;
        SELECT * INTO STORE_INFO
        FROM STORES_EMPLOYEE WHERE STORES_ID=S_STORES ;
        DBMS_OUTPUT.PUT_LINE(STORE_INFO.STORES_ID || '======>' || STORE_INFO.CITY );
END ;