
CREATE OR REPLACE PROCEDURE STORES_EMPLOYEE_PROCEDURE
(
    STORES_ID IN NUMBER,
    CITY IN VARCHAR2
)
AS
BEGIN
    INSERT INTO STORES_EMPLOYEE(STORES_ID,CITY)
    VALUES(STORES_ID,CITY);
END STORES_EMPLOYEE_PROCEDURE;



CREATE OR REPLACE FUNCTION STORES_EMPLOYEE_FUNCTION
(
    CITY  IN  VARCHAR2
)
RETURN NUMBER AS
    COUNT_STORES_EMPLOYEE NUMBER;

BEGIN

    SELECT COUNT(1) INTO COUNT_STORES_EMPLOYEE
    FROM STORES_EMPLOYEE WHERE CITY=CITY;

    RETURN COUNT_STORES_EMPLOYEE;

END STORES_EMPLOYEE_FUNCTION;


