
/*CREATING THE AUDIT RECORD */

CREATE TABLE AUDITLOG(
    U_ID NUMBER,
    USERNAME VARCHAR2(50),
    ONDATE DATE,
    ONTIME VARCHAR2(50),
    ONACTION VARCHAR2(50)
);

select * from AUDITLOG;

/*CREATING THE tRIGGER  RECORD  FOR LOGON */

CREATE OR REPLACE TRIGGER MY_SYS_TGR
AFTER LOGON ON DATABASE
DECLARE
    V_U_ID NUMBER;
    V_USERNAME VARCHAR2(50);
    V_ONDATE DATE;
    V_ONTIME VARCHAR2(50);
    V_ONACTION VARCHAR2(50);
BEGIN
    SELECT UID,USER,SYSDATE,TO_CHAR(SYSDATE,'HH24:MI') INTO V_U_ID,V_USERNAME,V_ONDATE,V_ONTIME
    FROM DUAL ;
    V_ONACTION:='LOGON';
    INSERT INTO AUDITLOG (U_ID,USERNAME,ONDATE,ONTIME,ONACTION) VALUES (V_U_ID,V_USERNAME,V_ONDATE,V_ONTIME,V_ONACTION);
    DBMS_OUTPUT.PUT_LINE('TRIGGER EXECUTED SUCCESSFULLY');
END;

/*CREATING THE tRIGGER  RECORD  FOR LOGOFF */

CREATE OR REPLACE TRIGGER MY_SYS_TGR_LOGOFF
BEFORE  LOGOFF  ON DATABASE
DECLARE
    V_U_ID NUMBER;
    V_USERNAME VARCHAR2(50);
    V_ONDATE DATE;
    V_ONTIME VARCHAR2(50);
    V_ONACTION VARCHAR2(50);
BEGIN
    SELECT UID,USER,SYSDATE,TO_CHAR(SYSDATE,'HH24:MI') INTO V_U_ID,V_USERNAME,V_ONDATE,V_ONTIME
    FROM DUAL ;
    V_ONACTION:='LOGOFF';
    INSERT INTO AUDITLOG (U_ID,USERNAME,ONDATE,ONTIME,ONACTION) VALUES (V_U_ID,V_USERNAME,V_ONDATE,V_ONTIME,V_ONACTION);
    DBMS_OUTPUT.PUT_LINE('TRIGGER EXECUTED SUCCESSFULLY');
END;

--LOGOFF

/*CREATING A USER JUST TO CHECK AND VALIDATE */

select sid,serial# from v$session where username = 'ADMIN';

CREATE USER PRAT IDENTIFIED BY Liverpool2022

GRANT CREATE SESSION TO PRAT

CONNECT PRAT/Liverpool2022


