/*USER DEFINDED  EXCEPTION */

CREATE OR REPLACE PROCEDURE STORES_EMP_NEW_PROC
(
    S_ID IN NUMBER
)
AS
    S_ID_NO STORES_EMPLOYEE.STORES_ID%TYPE;
    S_CITY STORES_EMPLOYEE.CITY%TYPE;
    S_CITY_EXCP EXCEPTION;

BEGIN

    IF S_ID<1000 THEN
        RAISE S_CITY_EXCP;
    ELSE
        SELECT STORES_ID,CITY INTO S_ID_NO,S_CITY
        FROM STORES_EMPLOYEE WHERE STORES_ID=S_ID;

        DBMS_OUTPUT.PUT_LINE(' STORES_ID: ' || S_ID_NO );
        DBMS_OUTPUT.PUT_LINE(' CITY: ' || S_CITY );
    END IF; 

EXCEPTION 
    WHEN S_CITY_EXCP THEN
    DBMS_OUTPUT.PUT_LINE(' STORES_ID MUST BE >1000' );
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR !!!' );

END STORES_EMP_NEW_PROC;

/*CALLING THE PROCEDURE */

BEGIN

STORES_EMP_NEW_PROC(S_ID=>100);

END;
