DECLARE 
SALES_DATE            SALES.SALES_DATE%TYPE;
ORDER_ID                SALES.ORDER_ID%TYPE;
PRODUCT_ID           SALES.PRODUCT_ID%TYPE;
CUSTOMER_ID        SALES.CUSTOMER_ID%TYPE;
SALESPERSON_ID      SALES.SALESPERSON_ID%TYPE;
QUANTITY_VALUE                SALES.QUANTITY_VALUE%TYPE;
UNIT_PRICE          SALES.UNIT_PRICE%TYPE;
SALES_AMOUNT        SALES.SALES_AMOUNT%TYPE;
TAX_AMOUNT          SALES.TAX_AMOUNT%TYPE;
TOTAL_AMOUNT        SALES.TOTAL_AMOUNT%TYPE;
BEGIN
    SELECT * 
    INTO   SALES_DATE,ORDER_ID,PRODUCT_ID,CUSTOMER_ID,SALESPERSON_ID,QUANTITY_VALUE,UNIT_PRICE,SALES_AMOUNT,TAX_AMOUNT,TOTAL_AMOUNT
    FROM SALES
    WHERE SALES_DATE='02-JAN-2015';
    

END;


DECLARE 
SALES_DATE            SALES.SALES_DATE%TYPE;
ORDER_ID              SALES.ORDER_ID%TYPE;
PRODUCT_ID            SALES.PRODUCT_ID%TYPE;
CUSTOMER_ID           SALES.CUSTOMER_ID%TYPE;
SALESPERSON_ID        SALES.SALESPERSON_ID%TYPE;
QUANTITY_VALUE              SALES.QUANTITY_VALUE%TYPE;
UNIT_PRICE            SALES.UNIT_PRICE%TYPE;
SALES_AMOUNT          SALES.SALES_AMOUNT%TYPE;
TAX_AMOUNT            SALES.TAX_AMOUNT%TYPE;
TOTAL_AMOUNT          SALES.TOTAL_AMOUNT%TYPE;
BEGIN
    SELECT S.SALES_DATE,S.ORDER_ID,S.PRODUCT_ID,S.CUSTOMER_ID,S.SALESPERSON_ID,S.QUANTITY_VALUE,S.UNIT_PRICE,S.SALES_AMOUNT,S.TAX_AMOUNT,S.TOTAL_AMOUNT
    INTO   SALES_DATE,ORDER_ID,PRODUCT_ID,CUSTOMER_ID,SALESPERSON_ID,QUANTITY_VALUE,UNIT_PRICE,SALES_AMOUNT,TAX_AMOUNT,TOTAL_AMOUNT
    FROM SALES S
    WHERE SALES_DATE='02-JAN-2015';
    
    DBMS_OUTPUT.PUT_LINE ('SALES_DATE :'  ||  TO_DATE (SALES_DATE, 'DD-MM-YYYY') );
    DBMS_OUTPUT.PUT_LINE('ORDER_ID:  ' ||  ORDER_ID);
    DBMS_OUTPUT.PUT_LINE(' CUSTOMER_ID:  '  || CUSTOMER_ID );
    DBMS_OUTPUT.PUT_LINE(' SALESPERSON_ID: '  || SALESPERSON_ID );
    DBMS_OUTPUT.PUT_LINE(' QUANTITY_VALUE: '  || QUANTITY_VALUE );
    DBMS_OUTPUT.PUT_LINE(' UNIT_PRICE  '    ||  UNIT_PRICE);
    DBMS_OUTPUT.PUT_LINE('SALES_AMOUNT  '   ||  SALES_AMOUNT);
    DBMS_OUTPUT.PUT_LINE(' TAX_AMOUNT  '    ||  TAX_AMOUNT);
    DBMS_OUTPUT.PUT_LINE(' TOTAL_AMOUNT  '  ||  TOTAL_AMOUNT );
        
    
END;


DECLARE 
SALES_DATE            SALES.SALES_DATE%TYPE:=TO_DATE('01-DEC-2015','DD-MM-YYYY');
ORDER_ID              SALES.ORDER_ID%TYPE:=15;
PRODUCT_ID            SALES.PRODUCT_ID%TYPE:=10;
CUSTOMER_ID           SALES.CUSTOMER_ID%TYPE:=250;
SALESPERSON_ID        SALES.SALESPERSON_ID%TYPE:=150;
QUANTITY_VALUE        SALES.QUANTITY_VALUE%TYPE:=220;
UNIT_PRICE            SALES.UNIT_PRICE%TYPE:=200;
SALES_AMOUNT          SALES.SALES_AMOUNT%TYPE:=500;
TAX_AMOUNT            SALES.TAX_AMOUNT%TYPE:=300;
TOTAL_AMOUNT          SALES.TOTAL_AMOUNT%TYPE:=1100;
BEGIN
    INSERT INTO SALES S (S.SALES_DATE,S.ORDER_ID,S.PRODUCT_ID,S.CUSTOMER_ID,S.SALESPERSON_ID,S.QUANTITY_VALUE,S.UNIT_PRICE,S.SALES_AMOUNT,S.TAX_AMOUNT,S.TOTAL_AMOUNT)
    VALUES (SALES_DATE,ORDER_ID,PRODUCT_ID,CUSTOMER_ID,SALESPERSON_ID,QUANTITY_VALUE,UNIT_PRICE,SALES_AMOUNT,TAX_AMOUNT,TOTAL_AMOUNT)
    
    
    DBMS_OUTPUT.PUT_LINE ('SALES_DATE :'  ||  TO_DATE (SALES_DATE, 'DD-MM-YYYY') );
    DBMS_OUTPUT.PUT_LINE('ORDER_ID:  ' ||  ORDER_ID);
    DBMS_OUTPUT.PUT_LINE(' CUSTOMER_ID:  '  || CUSTOMER_ID );
    DBMS_OUTPUT.PUT_LINE(' SALESPERSON_ID: '  || SALESPERSON_ID );
    DBMS_OUTPUT.PUT_LINE(' QUANTITY_VALUE: '  || QUANTITY_VALUE );
    DBMS_OUTPUT.PUT_LINE(' UNIT_PRICE  '    ||  UNIT_PRICE);
    DBMS_OUTPUT.PUT_LINE('SALES_AMOUNT  '   ||  SALES_AMOUNT);
    DBMS_OUTPUT.PUT_LINE(' TAX_AMOUNT  '    ||  TAX_AMOUNT);
    DBMS_OUTPUT.PUT_LINE(' TOTAL_AMOUNT  '  ||  TOTAL_AMOUNT );
        
    
END;





DECLARE 
SALES_DATE            SALES.SALES_DATE%TYPE:=TO_DATE('01-DEC-2015','DD-MM-YYYY');
ORDER_ID              SALES.ORDER_ID%TYPE:=15;
PRODUCT_ID            SALES.PRODUCT_ID%TYPE:=10;
CUSTOMER_ID           SALES.CUSTOMER_ID%TYPE:=250;
SALESPERSON_ID        SALES.SALESPERSON_ID%TYPE:=150;
QUANTITY_VALUE        SALES.QUANTITY_VALUE%TYPE:=220;
UNIT_PRICE            SALES.UNIT_PRICE%TYPE:=200;
SALES_AMOUNT          SALES.SALES_AMOUNT%TYPE:=500;
TAX_AMOUNT            SALES.TAX_AMOUNT%TYPE:=300;
TOTAL_AMOUNT          SALES.TOTAL_AMOUNT%TYPE:=1100;
BEGIN
    INSERT INTO SALES S (S.SALES_DATE,S.ORDER_ID,S.PRODUCT_ID,S.CUSTOMER_ID,S.SALESPERSON_ID,S.QUANTITY_VALUE,S.UNIT_PRICE,S.SALES_AMOUNT,S.TAX_AMOUNT,S.TOTAL_AMOUNT)
    VALUES (SALES_DATE,ORDER_ID,PRODUCT_ID,CUSTOMER_ID,SALESPERSON_ID,QUANTITY_VALUE,UNIT_PRICE,SALES_AMOUNT,TAX_AMOUNT,TOTAL_AMOUNT);
    
    DBMS_OUTPUT.PUT_LINE ('SALES_DATE :'  ||  SALES_DATE  );
    DBMS_OUTPUT.PUT_LINE('ORDER_ID:  ' ||  ORDER_ID);
    DBMS_OUTPUT.PUT_LINE(' CUSTOMER_ID:  '  || CUSTOMER_ID );
    DBMS_OUTPUT.PUT_LINE(' SALESPERSON_ID: '  || SALESPERSON_ID );
    DBMS_OUTPUT.PUT_LINE(' QUANTITY_VALUE: '  || QUANTITY_VALUE );
    DBMS_OUTPUT.PUT_LINE(' UNIT_PRICE  '    ||  UNIT_PRICE);
    DBMS_OUTPUT.PUT_LINE('SALES_AMOUNT  '   ||  SALES_AMOUNT);
    DBMS_OUTPUT.PUT_LINE(' TAX_AMOUNT  '    ||  TAX_AMOUNT);
    DBMS_OUTPUT.PUT_LINE(' TOTAL_AMOUNT  '  ||  TOTAL_AMOUNT );
        
    
END;
